USE [master]
GO

/****** Object:  Database [Assignment_1]    Script Date: 7/12/2021 1:31:18 AM ******/
CREATE DATABASE [Assignment_1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assignment_1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Assignment_1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Assignment_1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Assignment_1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assignment_1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Assignment_1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Assignment_1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Assignment_1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Assignment_1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Assignment_1] SET ARITHABORT OFF 
GO

ALTER DATABASE [Assignment_1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Assignment_1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Assignment_1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Assignment_1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Assignment_1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Assignment_1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Assignment_1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Assignment_1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Assignment_1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Assignment_1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Assignment_1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Assignment_1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Assignment_1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Assignment_1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Assignment_1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Assignment_1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Assignment_1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Assignment_1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Assignment_1] SET  MULTI_USER 
GO

ALTER DATABASE [Assignment_1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Assignment_1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Assignment_1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Assignment_1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Assignment_1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Assignment_1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Assignment_1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Assignment_1] SET  READ_WRITE 
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[cartIdTable](
	[cartID] [int] IDENTITY (1,1) NOT NULL,
	[customerName] [varchar](50) NULL,
	[customerAddress] [varchar](50) NULL,
 CONSTRAINT [PK_cartIdTable] PRIMARY KEY CLUSTERED 
(
	[cartID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[userTable](
	[username] [varchar](20) NOT NULL,
	[password] [varchar](30) NOT NULL,
	[lastname] [nvarchar](50) NOT NULL,
	[isAdmin] [bit] NOT NULL,
 CONSTRAINT [PK_userTable] PRIMARY KEY CLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[itemDetailsTable](
	[name] [varchar](50) NULL,
	[quantity] [int] NULL,
	[cartID] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[itemDetailsTable]  WITH CHECK ADD  CONSTRAINT [FK_itemDetailsTable_cartIdTable] FOREIGN KEY([cartID])
REFERENCES [dbo].[cartIdTable] ([cartID])
GO

ALTER TABLE [dbo].[itemDetailsTable] CHECK CONSTRAINT [FK_itemDetailsTable_cartIdTable]
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[product](
	[id] [int] NULL,
	[name] [varchar](10) NULL
) ON [PRIMARY]
GO